ad/mps
euro-hpc-pl/SpinGlassPEPS.jl pull request #30
Opened 2020-12-22 15:08 UTC by annamariadziubyna

2020-12-22 23:15 UTC, lpawela commented
@annamariadziubyna please provide a short summary of changes this PR introduces and also resolve any conflicts.

2020-12-23 09:49 UTC, bartekGardas requested changes
1. _apply_layer_of_gates takes way too many arguments, some of them are redundant, e.g., L (as it is already included in ig). In cases like this, we rather use MPScontrol.

2. What Dl1⊗Dl2 does, why not?

2020-12-23 09:54 UTC, bartekGardas requested changes
1. Instead of using setdiff(i+1:last(nbrs), nbrs), please define correct _holes from utils.jl.

2020-12-23 11:55 UTC, lpawela requested changes

2020-12-23 11:55 UTC, lpawela commented on src/spectrum.jl
> +        @cast B[(Dl1, Dl2), d, (Dr1, Dr2)] := A1[Dl1, d, Dr1] * A2[Dl2, d, Dr2]
Please follow the convention on index naming - greek vs latin letters

2020-12-23 11:55 UTC, lpawela commented on src/spectrum.jl
> +    if control.type == "log"
Too much code repetition

2020-12-23 11:55 UTC, lpawela commented on test/searchMPS.jl
> +@test sum(ϱ) ≈ 1
This is the only test in this file and it is trivial. Please ad some more tests.

2020-12-23 11:55 UTC, lpawela commented on Project.toml
> +Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Package that are listed under `[extras]` should not be here.

2021-01-18 11:14 UTC, lpawela approved these changes

2021-01-18 11:15 UTC, lpawela commented
@annamariadziubyna please resolve these conflits and then this can be merged

2021-01-26 10:17 UTC, lpawela commented
@annamariadziubyna please fix test coverage

2021-01-26 10:24 UTC, bartekGardas approved these changes
Let's merge now.

2021-01-26 11:39 UTC, merged